version: '3.8'
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  app:
    build:
      context: ./
    volumes:
      - ./:/var/www/app
    command: npm run start
    ports:
      - "3001:3001"
    links:
      - redis
    environment:
    - REDIS_URL=redis://cache
    - NODE_ENV=development
    - PORT=3001
    - SERVER_URL=test